Traceback (most recent call last):
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_comparado['RADIACAO_GLOBAL_IMPUTADA'] = df_comparado['RADIACAO_GLOBAL'].replace(0, pd.NA)
df_comparado['datetime'] = pd.to_datetime(df_comparado['datetime'])
df_comparado['dayofyear'] = df_comparado['datetime'].dt.dayofyear
df_comparado['hour'] = df_comparado['datetime'].dt.hour

tabla_promedios = df_comparado.groupby(['dayofyear', 'hour'])['RADIACAO_GLOBAL_IMPUTADA'].mean()
def imputar_estacional(row):
    if pd.isna(row['RADIACAO_GLOBAL_IMPUTADA']):
        return tabla_promedios.get((int(row['dayofyear']), int(row['hour'])), 0)
    else:
        return row['RADIACAO_GLOBAL_IMPUTADA']
df_comparado['RADIACAO_GLOBAL_IMPUTADA'] = df_comparado.apply(imputar_estacional, axis=1)
df_comparado['RADIACAO_GLOBAL_IMPUTADA'] = df_comparado['RADIACAO_GLOBAL_IMPUTADA'].fillna(0)
print(df_comparado.shape)
df_comparado.tail(20)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m df_comparado[[38;5;124m'[39m[38;5;124mRADIACAO_GLOBAL_IMPUTADA[39m[38;5;124m'[39m] [38;5;241m=[39m [43mdf_comparado[49m[[38;5;124m'[39m[38;5;124mRADIACAO_GLOBAL[39m[38;5;124m'[39m][38;5;241m.[39mreplace([38;5;241m0[39m, pd[38;5;241m.[39mNA)
[0;32m      2[0m df_comparado[[38;5;124m'[39m[38;5;124mdatetime[39m[38;5;124m'[39m] [38;5;241m=[39m pd[38;5;241m.[39mto_datetime(df_comparado[[38;5;124m'[39m[38;5;124mdatetime[39m[38;5;124m'[39m])
[0;32m      3[0m df_comparado[[38;5;124m'[39m[38;5;124mdayofyear[39m[38;5;124m'[39m] [38;5;241m=[39m df_comparado[[38;5;124m'[39m[38;5;124mdatetime[39m[38;5;124m'[39m][38;5;241m.[39mdt[38;5;241m.[39mdayofyear

[1;31mNameError[0m: name 'df_comparado' is not defined

