Traceback (most recent call last):
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Keyla Alba\.conda\envs\tf_gpu_py39\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
serie_hr = df_INMET['RADIACAO_GLOBAL_IMPUTADA'].fillna(0)

# Aplicar DWT a nivel 3 con wavelet 'db4'
wavelet = 'db4'
nivel = 3

serie_input = serie_hr.values
coeffs = pywt.wavedec(serie_input, wavelet=wavelet, level=nivel)

# Desempaquetar los coeficientes
A3, D3, D2, D1 = coeffs

# Visualizar resultados
plt.figure(figsize=(14, 8))

plt.subplot(4, 1, 1)
plt.plot(A3, color='black')
plt.title('AproximaciÃ³n A3 (tendencia general)')

plt.subplot(4, 1, 2)
plt.plot(D3, color='blue')
plt.title('Detalle D3 (baja frecuencia)')

plt.subplot(4, 1, 3)
plt.plot(D2, color='green')
plt.title('Detalle D2 (media frecuencia)')

plt.subplot(4, 1, 4)
plt.plot(D1, color='red')
plt.title('Detalle D1 (alta frecuencia)')

plt.tight_layout()
plt.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[38], line 8[0m
[0;32m      5[0m nivel [38;5;241m=[39m [38;5;241m3[39m
[0;32m      7[0m serie_input [38;5;241m=[39m serie_hr[38;5;241m.[39mvalues
[1;32m----> 8[0m coeffs [38;5;241m=[39m [43mpywt[49m[38;5;241m.[39mwavedec(serie_input, wavelet[38;5;241m=[39mwavelet, level[38;5;241m=[39mnivel)
[0;32m     10[0m [38;5;66;03m# Desempaquetar los coeficientes[39;00m
[0;32m     11[0m A3, D3, D2, D1 [38;5;241m=[39m coeffs

[1;31mNameError[0m: name 'pywt' is not defined

